spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_orfosys
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /orfosys

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: test_realm
  resource: ms.orfosys
  credentials:
    secret:
  cors: true
  cors-allowed-methods: POST, GET, PUT, DELETE
  securityConstraints[0]:
    securityCollections[0]:
      name: something
      patterns[0]: /orfosys
    authRoles[0]: ADMIN
