spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_dummy
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  security:
    resourceserver:
      oauth2:
        jwt:
          issuer-uri: http://localhost:8081/realms/JO
          jwk-set-uti: ${spring.security.resourceserver.oauth2.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  servlet:
    context-path: /app
