spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_dummy
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/JO
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  keycloak:
    client-id: java-spring3-keycloak

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: ${jwt.keycloak.client-id}
      client-secret: oYHXjHA4fu7vpfelIIosZFY00GpVmMpY
#     path: /swagger-ui/index.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /app

logging:
  level:
    org:
      keycloak: DEBUG


